In [1]:
import sys
import os
sys.path.append(os.path.abspath('..'))

import polars as pl

from config import (
    RAW_DATA_DIR,
    SAML_D_DATASET_HANDLE,
    SAML_D_FILE_NAME,
    SAML_D_INTERIM_PATH
)

from src.data.acquisition import KaggleDatasetDownloader
from src.data.loader import SAMLDDataLoader
from src.data.validation import SAMLDDataValidator
from src.data.preprocessing import SAMLDPreprocessor

In [2]:
### data acquisition
# create a downloader instance
downloader = KaggleDatasetDownloader(
    dataset_handle = SAML_D_DATASET_HANDLE,
    file_name = SAML_D_FILE_NAME,
    destination_dir = RAW_DATA_DIR
)

# download the raw SAML-D dataset
raw_data_path = downloader.download(
    force = False
)

raw_data_path

PosixPath('/Users/gorkemy/Desktop/Projects/Graph-based Financial Crime/data/raw/SAML-D.csv')

In [3]:
### data inspection
# create a loader instance
loader = SAMLDDataLoader(
    raw_data_path = raw_data_path
)

# create lazy query plan
raw_lazy_frame = loader.scan_raw()

# display LazyFrame schema
display(raw_lazy_frame.collect_schema())

# load a LazyFrame sample
raw_sample = loader.load_raw_sample(
    n_rows = 10_000
)

# inspect first 10 rows
display(raw_sample.head(10))

# inspecting the primary label
display(
    raw_sample
    .group_by('Is_laundering')
    .len()
)

Schema([('Time', String),
        ('Date', String),
        ('Sender_account', String),
        ('Receiver_account', String),
        ('Amount', Float64),
        ('Payment_currency', String),
        ('Received_currency', String),
        ('Sender_bank_location', String),
        ('Receiver_bank_location', String),
        ('Payment_type', String),
        ('Is_laundering', Int8),
        ('Laundering_type', String)])

shape: (10, 12)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Time     ┆ Date      ┆ Sender_ac ┆ Receiver_ ┆ … ┆ Receiver_ ┆ Payment_t ┆ Is_launde ┆ Launderin │
│ ---      ┆ ---       ┆ count     ┆ account   ┆   ┆ bank_loca ┆ ype       ┆ ring      ┆ g_type    │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ tion      ┆ ---       ┆ ---       ┆ ---       │
│          ┆           ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ i8        ┆ str       │
│          ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 10:35:19 ┆ 2022-10-0 ┆ 872473195 ┆ 276935542 ┆ … ┆ UK        ┆ Cash      ┆ 0         ┆ Normal_Ca │
│          ┆ 7         ┆ 5         ┆ 6         ┆   ┆           ┆ Deposit   ┆           ┆ sh_Deposi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ts        │
│ 10:35:20 ┆ 2022-10-0 ┆ 149198906 ┆ 840125533 ┆ … ┆ UAE       ┆ Cross-bor ┆ 0         ┆ Normal_Fa │
│          ┆ 7         ┆ 4         ┆ 5         ┆   ┆           ┆ der       ┆           ┆ n_Out     │
│ 10:35:20 ┆ 2022-10-0 ┆ 287305149 ┆ 440476700 ┆ … ┆ UK        ┆ Cheque    ┆ 0         ┆ Normal_Sm │
│          ┆ 7         ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 10:35:21 ┆ 2022-10-0 ┆ 537665243 ┆ 960042022 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Fa │
│          ┆ 7         ┆ 7         ┆ 0         ┆   ┆           ┆           ┆           ┆ n_In      │
│ 10:35:21 ┆ 2022-10-0 ┆ 961418617 ┆ 380333697 ┆ … ┆ UK        ┆ Cash      ┆ 0         ┆ Normal_Ca │
│          ┆ 7         ┆ 8         ┆ 2         ┆   ┆           ┆ Deposit   ┆           ┆ sh_Deposi │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ts        │
│ 10:35:21 ┆ 2022-10-0 ┆ 897455926 ┆ 314354751 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Gr │
│          ┆ 7         ┆ 8         ┆ 1         ┆   ┆           ┆           ┆           ┆ oup       │
│ 10:35:23 ┆ 2022-10-0 ┆ 980191499 ┆ 857763595 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_Sm │
│          ┆ 7         ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 10:35:23 ┆ 2022-10-0 ┆ 805779330 ┆ 935089621 ┆ … ┆ UK        ┆ Credit    ┆ 0         ┆ Normal_Sm │
│          ┆ 7         ┆ 8         ┆ 3         ┆   ┆           ┆ card      ┆           ┆ all_Fan_O │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ut        │
│ 10:35:26 ┆ 2022-10-0 ┆ 611665726 ┆ 656192169 ┆ … ┆ UK        ┆ Cheque    ┆ 0         ┆ Normal_Fa │
│          ┆ 7         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆ n_Out     │
│ 10:35:29 ┆ 2022-10-0 ┆ 742145175 ┆ 275570907 ┆ … ┆ UK        ┆ Credit    ┆ 0         ┆ Normal_Fa │
│          ┆ 7         ┆ 2         ┆ 1         ┆   ┆           ┆ card      ┆           ┆ n_Out     │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

shape: (2, 2)
┌───────────────┬──────┐
│ Is_laundering ┆ len  │
│ ---           ┆ ---  │
│ i8            ┆ u32  │
╞═══════════════╪══════╡
│ 1             ┆ 13   │
│ 0             ┆ 9987 │
└───────────────┴──────┘

In [4]:
### data validation
# raw data content validation
raw_content_summary = SAMLDDataValidator.validate_content(
    lazy_frame = raw_lazy_frame
)

raw_content_summary_frame = pl.DataFrame(
    [raw_content_summary]
)

with pl.Config(
    tbl_rows=-1
):
    display(
    raw_content_summary_frame
    .transpose(
        include_header = True,
        header_name = 'metric',
        column_names = ['value']
    )
)

shape: (23, 2)
┌─────────────────────────────────┬─────────┐
│ metric                          ┆ value   │
│ ---                             ┆ ---     │
│ str                             ┆ i64     │
╞═════════════════════════════════╪═════════╡
│ row_count                       ┆ 9504852 │
│ time_null_count                 ┆ 0       │
│ date_null_count                 ┆ 0       │
│ sender_account_null_count       ┆ 0       │
│ receiver_account_null_count     ┆ 0       │
│ amount_null_count               ┆ 0       │
│ payment_currency_null_count     ┆ 0       │
│ received_currency_null_count    ┆ 0       │
│ sender_bank_location_null_coun… ┆ 0       │
│ receiver_bank_location_null_co… ┆ 0       │
│ payment_type_null_count         ┆ 0       │
│ is_laundering_null_count        ┆ 0       │
│ laundering_type_null_count      ┆ 0       │
│ empty_sender_account_count      ┆ 0       │
│ empty_receiver_account_count    ┆ 0       │
│ nan_amount_count                ┆ 0       │
│ infinite_amount_count           ┆ 0       │
│ non_positive_amount_count       ┆ 0       │
│ invalid_label_count             ┆ 0       │
│ normal_transaction_count        ┆ 9494979 │
│ laundering_transaction_count    ┆ 9873    │
│ unparseable_timestamp_count     ┆ 0       │
│ self_transfer_count             ┆ 0       │
└─────────────────────────────────┴─────────┘

In [5]:
### data acquisition after Parquet conversion
# create preprocessor instance
preprocessor = SAMLDPreprocessor(
    raw_data_path = raw_data_path,
    interim_data_path = SAML_D_INTERIM_PATH
)

# convert raw dataset into parquet and write to interim data path
interim_data_path = preprocessor.convert_to_parquet(
    overwrite = False
)

interim_data_path

PosixPath('/Users/gorkemy/Desktop/Projects/Graph-based Financial Crime/data/interim/saml_d_transactions.parquet')

In [6]:
# data inspection after Parquet conversion
# create a interim loader instance
interim_loader = SAMLDDataLoader(
    raw_data_path = raw_data_path,
    interim_data_path = interim_data_path
)

# create a lazy query plan
interim_lazy_frame = interim_loader.scan_interim()

# display LazyFrame schema
display(interim_lazy_frame.collect_schema())

# load a LazyFrame interim sample
interim_sample = interim_loader.load_interim_sample(
    n_rows = 10_000
)

# inspect first 10 rows
display(interim_sample.head(10))

# inspecting the primary label
display(
    interim_sample
    .group_by('is_laundering')
    .len()
)

Schema([('transaction_id', UInt64),
        ('timestamp', Datetime(time_unit='us', time_zone=None)),
        ('sender_account', String),
        ('receiver_account', String),
        ('amount', Float64),
        ('payment_currency', String),
        ('received_currency', String),
        ('sender_bank_location', String),
        ('receiver_bank_location', String),
        ('payment_type', String),
        ('is_laundering', Int8),
        ('laundering_type', String)])

shape: (10, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transacti ┆ timestamp ┆ sender_ac ┆ receiver_ ┆ … ┆ receiver_ ┆ payment_t ┆ is_launde ┆ launderi │
│ on_id     ┆ ---       ┆ count     ┆ account   ┆   ┆ bank_loca ┆ ype       ┆ ring      ┆ ng_type  │
│ ---       ┆ datetime[ ┆ ---       ┆ ---       ┆   ┆ tion      ┆ ---       ┆ ---       ┆ ---      │
│ u64       ┆ μs]       ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ i8        ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 2022-10-0 ┆ 872473195 ┆ 276935542 ┆ … ┆ UK        ┆ Cash      ┆ 0         ┆ Normal_C │
│           ┆ 7         ┆ 5         ┆ 6         ┆   ┆           ┆ Deposit   ┆           ┆ ash_Depo │
│           ┆ 10:35:19  ┆           ┆           ┆   ┆           ┆           ┆           ┆ sits     │
│ 1         ┆ 2022-10-0 ┆ 149198906 ┆ 840125533 ┆ … ┆ UAE       ┆ Cross-bor ┆ 0         ┆ Normal_F │
│           ┆ 7         ┆ 4         ┆ 5         ┆   ┆           ┆ der       ┆           ┆ an_Out   │
│           ┆ 10:35:20  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 2022-10-0 ┆ 287305149 ┆ 440476700 ┆ … ┆ UK        ┆ Cheque    ┆ 0         ┆ Normal_S │
│           ┆ 7         ┆           ┆ 2         ┆   ┆           ┆           ┆           ┆ mall_Fan │
│           ┆ 10:35:20  ┆           ┆           ┆   ┆           ┆           ┆           ┆ _Out     │
│ 3         ┆ 2022-10-0 ┆ 537665243 ┆ 960042022 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_F │
│           ┆ 7         ┆ 7         ┆ 0         ┆   ┆           ┆           ┆           ┆ an_In    │
│           ┆ 10:35:21  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 2022-10-0 ┆ 961418617 ┆ 380333697 ┆ … ┆ UK        ┆ Cash      ┆ 0         ┆ Normal_C │
│           ┆ 7         ┆ 8         ┆ 2         ┆   ┆           ┆ Deposit   ┆           ┆ ash_Depo │
│           ┆ 10:35:21  ┆           ┆           ┆   ┆           ┆           ┆           ┆ sits     │
│ 5         ┆ 2022-10-0 ┆ 897455926 ┆ 314354751 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_G │
│           ┆ 7         ┆ 8         ┆ 1         ┆   ┆           ┆           ┆           ┆ roup     │
│           ┆ 10:35:21  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6         ┆ 2022-10-0 ┆ 980191499 ┆ 857763595 ┆ … ┆ UK        ┆ ACH       ┆ 0         ┆ Normal_S │
│           ┆ 7         ┆           ┆ 9         ┆   ┆           ┆           ┆           ┆ mall_Fan │
│           ┆ 10:35:23  ┆           ┆           ┆   ┆           ┆           ┆           ┆ _Out     │
│ 7         ┆ 2022-10-0 ┆ 805779330 ┆ 935089621 ┆ … ┆ UK        ┆ Credit    ┆ 0         ┆ Normal_S │
│           ┆ 7         ┆ 8         ┆ 3         ┆   ┆           ┆ card      ┆           ┆ mall_Fan │
│           ┆ 10:35:23  ┆           ┆           ┆   ┆           ┆           ┆           ┆ _Out     │
│ 8         ┆ 2022-10-0 ┆ 611665726 ┆ 656192169 ┆ … ┆ UK        ┆ Cheque    ┆ 0         ┆ Normal_F │
│           ┆ 7         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆ an_Out   │
│           ┆ 10:35:26  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9         ┆ 2022-10-0 ┆ 742145175 ┆ 275570907 ┆ … ┆ UK        ┆ Credit    ┆ 0         ┆ Normal_F │
│           ┆ 7         ┆ 2         ┆ 1         ┆   ┆           ┆ card      ┆           ┆ an_Out   │
│           ┆ 10:35:29  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (2, 2)
┌───────────────┬──────┐
│ is_laundering ┆ len  │
│ ---           ┆ ---  │
│ i8            ┆ u32  │
╞═══════════════╪══════╡
│ 0             ┆ 9987 │
│ 1             ┆ 13   │
└───────────────┴──────┘

In [7]:
### data validation after Parquet conversion
# validate row preservation and timestamp construction
interim_summary = (
    interim_lazy_frame
    .select(
        [
            pl.len()
            .alias(
                'row_count'
            ),
            pl.col('transaction_id')
            .n_unique()
            .alias(
                'unique_transaction_id'
            ),
            pl.col('timestamp')
            .null_count()
            .alias(
                'timestamp_null_count'
            ),
            pl.col('timestamp')
            .min()
            .alias(
                'minimum_timestamp'
            ),
            pl.col('timestamp')
            .max()
            .alias(
                'maximum_timestamp'
            )
        ]
    )
    .collect(
        engine = 'streaming'
    )
)

display(interim_summary)

# explicit row preservation 
interim_row_count = int(interim_summary['row_count'][0])
expected_row_count = int(raw_content_summary['row_count'])

if interim_row_count != expected_row_count:
    raise ValueError(
        'Raw-to-interim row count reconciliation failed. '
        f'Expected rows: {expected_row_count:,}, '
        f'Interim rows: {interim_row_count:,}.'
    )

print(
    'Raw-to-interim row count reconciliation passed. '
    f'Reconciled rows: {interim_row_count:,} rows'
)

shape: (1, 5)
┌───────────┬─────────────────────┬─────────────────────┬─────────────────────┬────────────────────┐
│ row_count ┆ unique_transaction_ ┆ timestamp_null_coun ┆ minimum_timestamp   ┆ maximum_timestamp  │
│ ---       ┆ id                  ┆ t                   ┆ ---                 ┆ ---                │
│ u32       ┆ ---                 ┆ ---                 ┆ datetime[μs]        ┆ datetime[μs]       │
│           ┆ u32                 ┆ u32                 ┆                     ┆                    │
╞═══════════╪═════════════════════╪═════════════════════╪═════════════════════╪════════════════════╡
│ 9504852   ┆ 9504852             ┆ 0                   ┆ 2022-10-07 10:35:19 ┆ 2023-08-23         │
│           ┆                     ┆                     ┆                     ┆ 10:57:12           │
└───────────┴─────────────────────┴─────────────────────┴─────────────────────┴────────────────────┘

Raw-to-interim row count reconciliation passed. Reconciled rows: 9,504,852 rows